### ISSUE TITLE
`hyper-graphdb` with `Hypercore 10` and `Autobase` ?

### ISSUE THREAD

**Issue by raphael10-collab** [fsteff/hyper-graphdb#1]
Are there any plans to "upgrade" `hyper-graphdb` to `Hypercore 10` and `Autobase` ?  
   https://github.com/hypercore-protocol/autobase

`hyper-graphdb` has great potential if based on multiwriter data structures: a P2P Multi-Writer GraphDb

**Comment by fsteff** [comment]
Unfortunately I see no clean way I can make hyper-graphdb's core dependency, [hyperobjects](https://github.com/fsteff/hyperobjects), compatible with autobase. The object IDs are sequential numbers an must be unique, you can't do that with multiple possibly offline writers. 

But I plan to build CertaCrypt's multiwriter approach ( [explained here](https://github.com/fsteff/certacrypt/blob/master/docs/multiwriter.md) ) into hyper-graphdb. But still applications will have to define their own conflict resolution algorithms.
